# importing libraries

In [1]:
import pandas as pd
import sklearn

# loading dataset

In [2]:
df = pd.read_csv('loan_prediction.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

# Basic info

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

# Check Missing Values

In [4]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# Handle Missing Values

In [5]:
df['Gender']

0        Male
1        Male
2        Male
3        Male
4        Male
        ...
609    Female
610      Male
611      Male
612      Male
613    Female
Name: Gender, Length: 614, dtype: str

In [6]:
#filling male in missing value
df['Gender'] = df['Gender'].fillna('male')

In [7]:
df['Gender'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
609    False
610    False
611    False
612    False
613    False
Name: Gender, Length: 614, dtype: bool

In [8]:
df['Married']

0       No
1      Yes
2      Yes
3      Yes
4       No
      ...
609     No
610    Yes
611    Yes
612    Yes
613     No
Name: Married, Length: 614, dtype: str

In [9]:
#filling yes in missing value
df['Married'] = df['Married'].fillna('Yes')

In [10]:
df['Dependents'].info()

<class 'pandas.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Dependents
Non-Null Count  Dtype
--------------  -----
599 non-null    str
dtypes: str(1)
memory usage: 4.9 KB

In [11]:
df['Dependents'] = df['Dependents'].replace('3+', 3)

In [12]:
df['Dependents'] = pd.to_numeric(df['Dependents'])

In [13]:
#filling dependents with median
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].median())

In [14]:
#filling self_employed with mode
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [15]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
#filling loanAmount with mean
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [17]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [18]:
#filling Loan_amount_term with mean
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean())

In [19]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [20]:
#filling credit_history with mode
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [21]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Remove Duplicates

In [22]:
df.drop_duplicates(inplace=True)

# Encode Categorical Data

In [23]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder

In [24]:
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents           float64
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [25]:
columns = ['Loan_ID','Gender','Married','Education','Self_Employed','Loan_Status']

In [26]:
#Label Encoder
encoders = {}

for col in columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le   # store encoder for each column

#One-hot encode Embarked

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder()

In [29]:
def area_to_numeric(x):
    if x == 'Urban':
        return 0
    if x == 'Rural':
        return 1
    if x == 'Semiurban':
        return 2

df['Property_Area'] = df['Property_Area'].apply(area_to_numeric)

In [30]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Feature Scaling

In [31]:
#standard Scaler
from sklearn.preprocessing import StandardScaler

In [32]:
scale_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

In [33]:
ss = StandardScaler()
df[scale_cols] = ss.fit_transform(df[scale_cols])

In [34]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,0,0.0,0,0,0.072991,-0.554487,0.000000,0.279851,1.0,0,1
1,1,1,1,1.0,0,0,-0.134412,-0.038732,-0.219273,0.279851,1.0,1,0
2,2,1,1,0.0,0,1,-0.393747,-0.554487,-0.957641,0.279851,1.0,0,1
3,3,1,1,0.0,1,0,-0.462062,0.251980,-0.314547,0.279851,1.0,0,1
4,4,1,0,0.0,0,0,0.097728,-0.554487,-0.064454,0.279851,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,0,0,0.0,0,0,-0.410130,-0.554487,-0.898095,0.279851,1.0,1,1
610,610,1,1,3.0,0,0,-0.212557,-0.554487,-1.267279,-2.518655,1.0,1,1
611,611,1,1,1.0,0,0,0.437174,-0.472404,1.269371,0.279851,1.0,0,1
612,612,1,1,2.0,0,0,0.357064,-0.554487,0.483367,0.279851,1.0,0,1
613,613,0,0,0.0,0,1,-0.134412,-0.554487,-0.159728,0.279851,0.0,2,0

# feature Selection

In [35]:
#Feature Selection
X = df.iloc[:,[0,5,6,7,8,9,10,11]]
y = df.iloc[:,12]

In [36]:
X,y

(     Loan_ID  Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  \
 0          0              0         0.072991          -0.554487    0.000000
 1          1              0        -0.134412          -0.038732   -0.219273
 2          2              1        -0.393747          -0.554487   -0.957641
 3          3              0        -0.462062           0.251980   -0.314547
 4          4              0         0.097728          -0.554487   -0.064454
 ..       ...            ...              ...                ...         ...
 609      609              0        -0.410130          -0.554487   -0.898095
 610      610              0        -0.212557          -0.554487   -1.267279
 611      611              0         0.437174          -0.472404    1.269371
 612      612              0         0.357064          -0.554487    0.483367
 613      613              1        -0.134412          -0.554487   -0.159728

      Loan_Amount_Term  Credit_History  Property_Area
 0            0.279851             1.0              0
 1            0.279851             1.0              1
 2            0.279851             1.0              0
 3            0.279851             1.0              0
 4            0.279851             1.0              0
 ..                ...             ...            ...
 609          0.279851             1.0              1
 610         -2.518655             1.0              1
 611          0.279851             1.0              0
 612          0.279851             1.0              0
 613          0.279851             0.0              2

 [614 rows x 8 columns],
 0      1
 1      0
 2      1
 3      1
 4      1
       ..
 609    1
 610    1
 611    1
 612    1
 613    0
 Name: Loan_Status, Length: 614, dtype: int64)

# Train_test_split

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [38]:
print(X_train.shape),
print(X_test.shape),
print(y_train.shape),
print(y_test.shape)

(429, 8)
(185, 8)
(429,)
(185,)