In [1]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in .\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 6.7 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.7 MB/s  0:00:00
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading greenlet-3.4.0-cp310-cp310-win_amd64.whl (237 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.4.0 pymysql-1.1.2 sqlalchemy-2.0.49

# Import Libraries

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Load CSV Dataset

In [2]:
df = pd.read_csv("employees.csv")
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

# Connect MySQL from Jupyter

In [3]:
engine = create_engine("mysql+pymysql://root:khan%40123@localhost/companydb")

# Upload CSV into MySQL Table

In [4]:
df.to_sql("employees", con=engine, if_exists="replace", index=False)

1000

In [5]:
result = pd.read_sql("SELECT * FROM employees LIMIT 5;", engine)
print(result)

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

   Senior Management             Team
0                  1        Marketing
1                  1             None
2                  0          Finance
3                  1          Finance
4                  1  Client Services

# check table structure

In [6]:
pd.read_sql("SHOW COLUMNS FROM employees;", engine)

               Field        Type Null Key Default Extra
0         First Name        text  YES        None
1             Gender        text  YES        None
2         Start Date        text  YES        None
3    Last Login Time        text  YES        None
4             Salary      bigint  YES        None
5            Bonus %      double  YES        None
6  Senior Management  tinyint(1)  YES        None
7               Team        text  YES        None

# Count Total Rows

In [7]:
pd.read_sql("SELECT COUNT(*) AS total_rows FROM employees;", engine)

   total_rows
0        1000

# Renaming columns

In [8]:
#rename first name
with engine.begin() as conn:
    conn.exec_driver_sql("""
    ALTER TABLE employees
    RENAME COLUMN `First Name` TO First_Name;
    """)

In [9]:
#rename Start date
with engine.begin() as conn:
    conn.exec_driver_sql("""
    ALTER TABLE employees
    RENAME COLUMN `Start Date` TO Start_Date;
    """)

In [10]:
#rename last login time
with engine.begin() as conn:
    conn.exec_driver_sql("""
    ALTER TABLE employees
    RENAME COLUMN `Last Login Time` TO Last_Login_Time;
    """)

In [12]:
#rename Bonus % 
with engine.begin() as conn:
    conn.exec_driver_sql("""
    ALTER TABLE employees
    RENAME COLUMN `Bonus %%` TO Bonus;
    """)

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Bonus %' in 'employees'")
[SQL:
    ALTER TABLE employees
    RENAME COLUMN `Bonus %%` TO Bonus;
    ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [15]:
#rename senior management
with engine.begin() as conn:
    conn.exec_driver_sql("""
    ALTER TABLE employees
    RENAME COLUMN `Senior Management` TO Senior_Management;
    """)

In [16]:
pd.read_sql("SELECT * FROM employees LIMIT 5;",engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,1,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,1,None
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,0,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,1,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,1,Client Services

# DATA HANDLING OPERATIONS
# Select Specific Columns

In [17]:
pd.read_sql("""
SELECT First_Name, Salary
FROM employees;
""", engine)

    First_Name  Salary
0      Douglas   97308
1       Thomas   61933
2        Maria  130590
3        Jerry  138705
4        Larry  101004
..         ...     ...
995      Henry  132483
996    Phillip   42392
997    Russell   96914
998      Larry   60500
999     Albert  129949

[1000 rows x 2 columns]

# Filter Records

In [18]:
#Employees with salary above 50000:
pd.read_sql("""
SELECT *
FROM employees
WHERE Salary > 50000;
""", engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,1.0,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,1.0,None
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,0.0,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,1.0,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,1.0,Client Services
...,...,...,...,...,...,...,...,...
849,George,Male,6/21/2013,5:47 PM,98874,4.479,1.0,Marketing
850,Henry,None,11/23/2014,6:09 AM,132483,16.655,0.0,Distribution
851,Russell,Male,5/20/2013,12:39 PM,96914,1.421,0.0,Product
852,Larry,Male,4/20/2013,4:45 PM,60500,11.985,0.0,Business Development
853,Albert,Male,5/15/2012,6:24 PM,129949,10.169,1.0,Sales

# Sort Data

In [19]:
#Highest salary first:
pd.read_sql("""
SELECT *
FROM employees
ORDER BY Salary DESC;
""", engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Katherine,Female,8/13/1996,12:21 AM,149908,18.912,0.0,Finance
1,Rose,Female,5/28/2015,8:40 AM,149903,5.630,0.0,Human Resources
2,Cynthia,Female,7/12/2006,8:55 AM,149684,7.864,0.0,Product
3,None,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales
4,Kathy,Female,3/18/2000,7:26 PM,149563,16.991,1.0,Finance
...,...,...,...,...,...,...,...,...
995,Cynthia,Female,7/5/1986,1:24 AM,35381,11.749,0.0,Finance
996,Matthew,Male,1/2/2013,10:33 PM,35203,18.040,0.0,Human Resources
997,Steven,Male,3/30/1980,9:20 PM,35095,8.379,1.0,Client Services
998,Kevin,Male,3/25/1982,7:31 AM,35061,5.128,0.0,Legal
999,Michael,Male,7/30/1993,5:35 PM,35013,14.879,0.0,Product

# Count Total Employees

In [20]:
pd.read_sql("""
SELECT COUNT(*) AS total_employees
FROM employees;
""", engine)

   total_employees
0             1000

# Average Salary

In [21]:
pd.read_sql("""
SELECT AVG(Salary) AS avg_salary
FROM employees;
""", engine)

   avg_salary
0   90662.181

# Group By Team

In [22]:
pd.read_sql("""
SELECT Team, COUNT(*) AS total_staff
FROM employees
GROUP BY Team;
""", engine)

                    Team  total_staff
0              Marketing           98
1                   None           43
2                Finance          102
3        Client Services          106
4                  Legal           88
5                Product           95
6            Engineering           92
7   Business Development          101
8        Human Resources           91
9                  Sales           94
10          Distribution           90

# Team Wise Salary

In [23]:
pd.read_sql("""
SELECT Team, AVG(Salary) AS avg_salary
FROM employees
GROUP BY Team;
""", engine)

                    Team  avg_salary
0              Marketing  90435.5918
1                   None  90763.1395
2                Finance  92219.4804
3        Client Services  88224.4245
4                  Legal  89303.6136
5                Product  88665.5053
6            Engineering  94269.1957
7   Business Development  91866.3168
8        Human Resources  90944.5275
9                  Sales  92173.4362
10          Distribution  88500.4667

# Find Missing Values

In [24]:
pd.read_sql("""
SELECT *
FROM employees
WHERE First_Name IS NULL
   OR Gender IS NULL
   OR Start_Date IS NULL
   OR Last_Login_Time IS NULL
   OR Salary IS NULL
   OR Bonus IS NULL
   OR Senior_Management IS NULL
   OR Team IS NULL;
""", engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,1.0,None
1,None,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
2,Louise,Female,8/12/1980,9:01 AM,63241,15.132,1.0,None
3,Lois,None,4/22/1995,7:18 PM,64714,4.934,1.0,Legal
4,Joshua,None,3/8/2012,1:58 AM,90816,18.816,1.0,Client Services
...,...,...,...,...,...,...,...,...
231,Antonio,None,6/18/1989,9:37 PM,103050,3.050,0.0,Legal
232,Victor,None,7/28/2006,2:49 PM,76381,11.159,1.0,Sales
233,Stephen,None,7/10/1983,8:10 PM,85668,1.909,0.0,Legal
234,Justin,None,2/10/1991,4:58 PM,38344,3.794,0.0,Legal
235,Henry,None,11/23/2014,6:09 AM,132483,16.655,0.0,Distribution

# Count Missing Values Column Wise

In [25]:
pd.read_sql("""
SELECT
SUM(CASE WHEN First_Name IS NULL THEN 1 ELSE 0 END) AS First_Name_missing,
SUM(CASE WHEN Gender IS NULL THEN 1 ELSE 0 END) AS Gender_missing,
SUM(CASE WHEN Start_Date IS NULL THEN 1 ELSE 0 END) AS Start_Date_missing,
SUM(CASE WHEN Last_Login_Time IS NULL THEN 1 ELSE 0 END) AS Last_Login_missing,
SUM(CASE WHEN Salary IS NULL THEN 1 ELSE 0 END) AS Salary_missing,
SUM(CASE WHEN Bonus IS NULL THEN 1 ELSE 0 END) AS Bonus_missing,
SUM(CASE WHEN Senior_Management IS NULL THEN 1 ELSE 0 END) AS Senior_Management_missing,
SUM(CASE WHEN Team IS NULL THEN 1 ELSE 0 END) AS Team_missing
FROM employees;
""", engine)

,First_Name_missing,Gender_missing,Start_Date_missing,Last_Login_missing,Salary_missing,Bonus_missing,Senior_Management_missing,Team_missing
0,67.0,145.0,0.0,0.0,0.0,0.0,67.0,43.0

# Handle Missing Values

In [33]:
# Fill Missing Team
with engine.begin() as conn:
    conn.exec_driver_sql("""
    UPDATE employees
    SET Team = 'Unknown'
    WHERE Team IS NULL;
    """)

In [34]:
# Fill Missing Gender
with engine.begin() as conn:
    conn.exec_driver_sql("""
    UPDATE employees
    SET Gender = 'Unknown'
    WHERE Gender IS NULL;
    """)

In [35]:
# Fill Missing Senior Management
with engine.begin() as conn:
    conn.exec_driver_sql("""
    UPDATE employees
    SET Senior_Management = 0
    WHERE Senior_Management IS NULL;
    """)

# Delete Missing First_Name
#Name is important. Better to remove.

In [36]:
with engine.begin() as conn:
    conn.exec_driver_sql("""
    DELETE FROM employees
    WHERE First_Name IS NULL;
    """)

# Find Rows Containing Missing Values

In [37]:
pd.read_sql("""
SELECT *
FROM employees
WHERE First_Name IS NULL
   OR Gender IS NULL
   OR Team IS NULL
   OR Senior_Management IS NULL;
""", engine)

Empty DataFrame
Columns: [First_Name, Gender, Start_Date, Last_Login_Time, Salary, Bonus, Senior_Management, Team]
Index: []

# filter

In [39]:
# selecting employees whose Team is Finance
pd.read_sql("""
SELECT *
FROM employees
WHERE Team = 'Finance';
""", engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Maria,Female,4/23/1993,11:17 AM,130590,11.858,0,Finance
1,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,1,Finance
2,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,1,Finance
3,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,0,Finance
4,Alan,Unknown,3/3/2014,1:28 PM,40341,17.578,1,Finance
...,...,...,...,...,...,...,...,...
92,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,0,Finance
93,Joe,Male,1/19/1980,4:06 PM,119667,1.148,1,Finance
94,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,1,Finance
95,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,1,Finance
96,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,0,Finance

# group and count by Team

In [28]:
pd.read_sql("""
SELECT Team, COUNT(*) AS total_emp
FROM employees
GROUP BY Team;
""", engine)

                    Team  total_emp
0              Marketing         98
1                   None         43
2                Finance        102
3        Client Services        106
4                  Legal         88
5                Product         95
6            Engineering         92
7   Business Development        101
8        Human Resources         91
9                  Sales         94
10          Distribution         90

# Group and Average Salary by Team

In [34]:
pd.read_sql("""
SELECT Team, AVG(Salary) AS avg_salary
FROM employees
GROUP BY Team
ORDER BY avg_salary DESC;
""", engine)

                    Team  avg_salary
0            Engineering  94581.8372
1                  Sales  92746.4419
2                Finance  92733.4433
3   Business Development  91393.6364
4              Marketing  90625.0879
5                  Legal  89806.7558
6        Human Resources  89751.3412
7        Client Services  88445.0700
8                Product  87715.9891
9           Distribution  86680.1818
10               Unknown  85241.7941

# Count by Senior_Management

In [35]:
pd.read_sql("""
SELECT Senior_Management, COUNT(*) AS total
FROM employees
GROUP BY Senior_Management;
""", engine)

   Senior_Management  total
0                  1    468
1                  0    465

# cleaned data load as csv

In [36]:
cleaned = pd.read_sql("SELECT * FROM employees;", engine)
cleaned.to_csv("cleaned_employees.csv", index=False)

In [29]:
pd.read_sql("SELECT * FROM employees LIMIT 20;", engine)

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,1.0,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,1.0,None
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,0.0,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,1.0,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,1.0,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,0.0,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,1.0,Product
7,None,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,1.0,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,1.0,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,1.0,None
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,1.0,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,1.0,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,0.0,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,1.0,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,0.0,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,0.0,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,0.0,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,0.0,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,0.0,Product

In [31]:
pd.read_sql("SHOW COLUMNS FROM employees;", engine)

               Field        Type Null Key Default Extra
0         First_Name        text  YES        None
1             Gender        text  YES        None
2         Start_Date        text  YES        None
3    Last_Login_Time        text  YES        None
4             Salary      bigint  YES        None
5              Bonus      double  YES        None
6  Senior_Management  tinyint(1)  YES        None
7               Team        text  YES        None